
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: xxxxxxxxxxx

xiaomi_mac: xxxxxxxxxxxx
xiaomi_key: xxxxxxxxxxxxxxxx

spotify_id: xxxxxxxxxxx
spotify_secret: xxxxxxxxxxx

router_ip: 127.0.0.1
router_user: xxxxxxxxxxx
router_pass: xxxxxxxxxxx

home_latitude: 0
home_longitude: 0

ssl_cert: fullchain.pem
ssl_key: privkey.pem
ssl_url: xxxxxxxxxxx
ssl_cmd: xxxxxxxxxxx

sonos_url1: 127.0.0.1
sonos_url2: 127.0.0.1
symfonisk_url1: 127.0.0.1

chromecast_url: 127.0.0.1

trafikverket: xxxxxxxxxxx