notifications:
  email:
    on_success: never 
    on_failure: never 

language: python
python:
  - 3.5
  - 3.6

before_install:
  - mv .travis_secrets.yaml secrets.yaml
  - touch fullchain.pem
  - touch privkey.pem
install:
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config