notifications:
  email:
    on_success: never 
    on_failure: never 

language: python
python:
  - 3.5
  - 3.6

before_install:
  - mv .travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config