homeassistant:
  name: Home
  country: SE
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 9
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

frontend:
  #javascript_version: latest
  #themes: !include_dir_named themes

lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/hass-bha-icons/hass-bha-icons.js
    type: module

config:

system_health:

mobile_app:

http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

person:
  - name: Markus
    id: markus123
    user_id: 9652dc85ce384db281ec2f85c9605291
    device_trackers:
      - device_tracker.iphone

discovery:

conversation:

tellduslive:

history:
  exclude:
    domains:
      - sun

recorder:
  purge_keep_days: 5

logbook:

map:

sun:

sonos:
  media_player:
    hosts:
      - !secret sonos_url1
      - !secret sonos_url2
      - !secret symfonisk_url1
      - !secret symfonisk_url2

sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_cmd

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Zones
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 20
    icon: mdi:home-circle

shell_command: 
  renew_ssl: certbot renew


automation: !include_dir_merge_list automations
script: !include scripts.yaml
