homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 9
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

frontend:
  javascript_version: latest
  #themes: !include_dir_named themes

lovelace:
  mode: yaml

config:

system_health:

custom_updater:
  track:
    - cards
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

ios:

mobile_app:

http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret ssl_url

updater:

discovery:

conversation:

tellduslive:

history:
  exclude:
    domains:
      - sun

recorder:      
  purge_interval: 2
  purge_keep_days: 5

logbook:

map:

sun:

# homekit:

sonos:
  media_player:
    hosts:
      - !secret sonos_url1
      - !secret sonos_url2

sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol

  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_cmd

  - platform: template
    sensors:
      button1_battery:
        friendly_name: 'Knapp 1'
        value_template: "{{ states.binary_sensor.switch_158d000288c41c.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      button2_battery:
        friendly_name: 'Knapp 2'
        value_template: "{{ states.binary_sensor.switch_158d00028a6f95.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      button3_battery:
        friendly_name: 'Knapp 3'
        value_template: "{{ states.binary_sensor.switch_158d00029012ef.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      door1_battery:
        friendly_name: 'Dörr Ytterdörr'
        value_template: "{{ states.binary_sensor.door_window_sensor_158d0002011681.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      door2_battery:
        friendly_name: 'Dörr Uterum'
        value_template: "{{ states.binary_sensor.door_window_sensor_158d0002277ebf.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      forrad_temp_battery:
        friendly_name: 'Förråd Temp'
        value_template: "{{ states.sensor.temperature_158d0001c1c07a.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      sovrum_temp_battery:
        friendly_name: 'Sovrum Temp'
        value_template: "{{ states.sensor.temperature_158d0001c2c4e4.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      uterum_temp_battery:
        friendly_name: 'Uterum Temp'
        value_template: "{{ states.sensor.temperature_158d0001c2c54c.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70
      vardagsrum_temp_battery:
        friendly_name: 'Vardagsrum Temp'
        value_template: "{{ states.sensor.temperature_158d000201d362.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: mdi:battery-70


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Zones
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 20
    icon: mdi:home-circle

# Device Tracker
device_tracker:
  - platform: netgear
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pass
    consider_home: 960


# Xiaomi Gateway
xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key

shell_command: 
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01 --pre-hook "sudo systemctl stop home-assistant@homeassistant.service" --post-hook "sudo systemctl start home-assistant@homeassistant.service"


automation: !include_dir_merge_list automations
script: !include scripts.yaml
