title: Home
views:
  - title: Home
    path: home
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Vardagsrum
        show_header_toggle: true
        entities:
          - switch.fonsterlampa_orange
          - switch.brytare8
          - binary_sensor.openclose_dorr1
          - binary_sensor.openclose_dorr2

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temp Vardagsrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.temperatur_vardagsrum
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 22
                color: "#00FF00"
              - value: 25
                color: "#FF0000"
          - type: custom:mini-graph-card
            name: Luftfuktighet Vardagsrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.temperatur_vardagsrum_2
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 20
                color: "#00FF00"
              - value: 40
                color: "#FF0000"

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperatur_uterum
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 22
                    color: "#00FF00"
                  - value: 25
                    color: "#FF0000"
              - type: custom:mini-graph-card
                name: Luftfuktighet Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperatur_uterum_2
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 20
                    color: "#00FF00"
                  - value: 40
                    color: "#FF0000"
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperatur_forrad
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 22
                    color: "#00FF00"
                  - value: 25
                    color: "#FF0000"
              - type: custom:mini-graph-card
                name: Luftfuktighet Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperatur_forrad_2
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 20
                    color: "#00FF00"
                  - value: 40
                    color: "#FF0000"

          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Sovrum
                height: 75
                show:
                      fill: fade
                entities:
                  - sensor.temperatur_sovrum
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 22
                    color: "#00FF00"
                  - value: 25
                    color: "#FF0000"
              - type: custom:mini-graph-card
                name: Luftfuktighet Sovrum
                height: 75
                show:
                      fill: fade
                entities:
                  - sensor.temperatur_sovrum_2
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 20
                    color: "#00FF00"
                  - value: 40
                    color: "#FF0000"

      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: switch.brytare6
            image: /local/nightlight.jpg
            tap_action:
              action: toggle
          - type: picture-entity
            entity: switch.ljusslinga
            image: /local/ljusslinga.jpg
            tap_action:
              action: toggle
              
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: switch.kokslampor
            image: /local/windowlight.jpg
            tap_action:
              action: toggle
          - type: picture-entity
            entity: switch.fonsterlampa_vit
            image: /local/floorlight.png
            tap_action:
              action: toggle

      - type: entities
        title: Övrigt
        show_header_toggle: false
        entities:
          - person.markus
          - sun.sun
          - sensor.postnord_delivery_27431
          - binary_sensor.home_assistant_versions_update_available
          - sensor.home_assistant_versions
          - sensor.hacs

      - type: entities
        title: Tåg
        show_header_toggle: false
        entities:
          - sensor.skurup_to_hyllie_at_07_17
          - sensor.hyllie_to_skurup_at_16_45

      - type: gauge
        name: SSL Cert Expiry
        entity: sensor.ssl_cert_expiry
        min: 0
        max: 90
        severity:
          green: 45
          yellow: 20
          red: 0

      - type: weather-forecast
        entity: weather.smhi_skurup

      - type: history-graph
        title: 'Temperatures'
        hours_to_show: 72
        refresh_interval: 600
        entities:
          - sensor.temperatur_vardagsrum
          - sensor.temperatur_forrad
          - sensor.temperatur_uterum
          - sensor.temperatur_sovrum

      - type: vertical-stack
        cards:
        - type: custom:mini-media-player
          entity: media_player.vardagsrum
          name: Vardagsrum
          artwork: cover
          source: icon
          hide:
            shuffle: true

        - type: custom:mini-media-player
          entity: media_player.kok
          name: Kök
          artwork: cover
          source: icon
          hide:
            shuffle: true

        - type: custom:mini-media-player
          entity: media_player.uterum_v
          name: Uterum
          artwork: cover
          source: icon
          hide:
            shuffle: true

      - type: custom:mini-media-player
        entity: media_player.vardagsrum_2
        name: Vardagsrum-ChromeCast
        artwork: cover
        source: icon
        hide:
          shuffle: true

  - title: Automations
    icon: mdi:auto-fix
    path: auto
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - automation.hass_new_device_tracked
          - automation.hass_started
          - automation.hass_updater
          - automation.renew_ssl_cert
          - automation.slack_ljus_vid_01_00
          - automation.slack_ljus_vid_07_00
          - automation.slack_ljus_vid_midnatt
          - automation.ssl_expiry_notification
          - automation.tand_ljus_60_min_innan_solnedgang
          - automation.tand_ljus_vid_19_15
          - automation.tand_tv_rum

  - title: Batteries
    icon: mdi:battery-charging-40
    path: batt
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.openclose_dorr1_battery_level
          - sensor.openclose_dorr2_battery_level
          - sensor.switch_c41c_battery_level
          - sensor.switch_12ef_battery_level
          - sensor.switch_6f95_battery_level
          - sensor.temperatur_forrad_battery_level
          - sensor.temperatur_sovrum_battery_level
          - sensor.temperatur_uterum_battery_level
          - sensor.temperatur_vardagsrum_battery_level
