resources:
  - url: /customcards/mini-graph-card-bundle.js?track=true
    type: module
  - url: /customcards/mini-media-player-bundle.js?track=true
    type: module
  - url: /customcards/tracker-card.js?track=true
    type: module

title: Home
views:
  - title: Home
    path: home
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Vardagsrum
        show_header_toggle: true
        entities:
          - switch.fonsterlampa_orange
          - switch.fonsterlampa_vit
          - switch.golvlampa
          - switch.ljusslinga
          - switch.kokslampor
          - light.gateway_light_7811dcb1ff16
          - sensor.illumination_7811dcb1ff16
          - binary_sensor.door_window_sensor_158d0002277ebf
          - binary_sensor.door_window_sensor_158d0002011681

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temp Vardagsrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.temperature_158d000201d362
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 22
                color: "#00FF00"
              - value: 25
                color: "#FF0000"
          - type: custom:mini-graph-card
            name: Luftfuktighet Vardagsrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.humidity_158d000201d362
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 20
                color: "#00FF00"
              - value: 40
                color: "#FF0000"

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperature_158d0001c2c54c
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 22
                    color: "#00FF00"
                  - value: 25
                    color: "#FF0000"
              - type: custom:mini-graph-card
                name: Luftfuktighet Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.humidity_158d0001c2c54c
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 20
                    color: "#00FF00"
                  - value: 40
                    color: "#FF0000"
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperature_158d0001c1c07a
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 22
                    color: "#00FF00"
                  - value: 25
                    color: "#FF0000"
              - type: custom:mini-graph-card
                name: Luftfuktighet Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.humidity_158d0001c1c07a
                color_thresholds:
                  - value: 0
                    color: "#0000FF"
                  - value: 20
                    color: "#00FF00"
                  - value: 40
                    color: "#FF0000"

      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: switch.sovrum
            image: /local/ljusslinga.jpg
            tap_action:
              action: toggle
          - type: picture-entity
            entity: switch.brytare7
            image: /local/ljusslinga.jpg
            tap_action:
              action: toggle

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temp Sovrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.temperature_158d0001c2c4e4
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 22
                color: "#00FF00"
              - value: 25
                color: "#FF0000"
          - type: custom:mini-graph-card
            name: Luftfuktighet Sovrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.humidity_158d0001c2c4e4
            color_thresholds:
              - value: 0
                color: "#0000FF"
              - value: 20
                color: "#00FF00"
              - value: 40
                color: "#FF0000"

      - type: entities
        title: Övrigt
        show_header_toggle: false
        entities:
          - device_tracker.iphone_2
          - sensor.ssl_cert_expiry
          - sun.sun
          - updater.updater

      - type: custom:tracker-card

      - type: weather-forecast
        entity: weather.smhi_skurup

      - type: history-graph
        title: 'Temperatures'
        hours_to_show: 144
        refresh_interval: 600
        entities:
          - sensor.temperature_158d0001c2c4e4
          - sensor.temperature_158d000201d362
          - sensor.temperature_158d0001c1c07a
          - sensor.temperature_158d0001c2c54c

      - type: custom:mini-media-player
        entity: media_player.vardagsrum
        name: Vardagsrum
        artwork: cover
        source: icon
        hide:
          shuffle: true

      - type: custom:mini-media-player
        entity: media_player.kok
        name: Kök
        artwork: cover
        source: icon
        hide:
          shuffle: true

  - title: Automations
    icon: mdi:auto-fix
    path: auto
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - automation.hass_new_device_tracked
          - automation.hass_started
          - automation.hass_updater
          - automation.ifttt_trigger_automation
          - automation.renew_ssl_cert
          - automation.slack_ljus_vid_01_00
          - automation.slack_ljus_vid_20_00
          - automation.slack_ljus_vid_midnatt
          - automation.slack_xaoimi_gateway_rgb
          - automation.ssl_expiry_notification
          - automation.styr_xaoimi_gateway_rgb
          - automation.tand_ljus_19_00

  - title: Batteries
    icon: mdi:battery-charging-40
    path: batt
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.flower1_battery
          - sensor.flower2_battery
          - sensor.door1_battery
          - sensor.door2_battery
          - sensor.button1_battery
          - sensor.button2_battery
          - sensor.button3_battery
          - sensor.forrad_temp_battery
          - sensor.sovrum_temp_battery
          - sensor.uterum_temp_battery
          - sensor.vardagsrum_temp_battery
