resources:
  - url: /customcards/mini-graph-card-bundle.js
    type: module
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/tracker-card.js
    type: js

title: Home
views:
  - title: Home
    path: home
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Vardagsrum
        show_header_toggle: true
        entities:
          - switch.fonsterlampa_orange
          - switch.fonsterlampa_vit
          - switch.golvlampa
          - switch.ljusslinga
          - switch.kokslampor
          - light.gateway_light_7811dcb1ff16
          - sensor.illumination_7811dcb1ff16
          - sensor.temperature_158d000201d362
          - sensor.humidity_158d000201d362
          - binary_sensor.door_window_sensor_158d0002277ebf

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperature_158d0001c2c54c
                color_thresholds:
                  - value: 0
                    color: blue
                  - value: 22
                    color: green
                  - value: 25
                    color: red
              - type: custom:mini-graph-card
                name: Luftfuktighet Uterum
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.humidity_158d0001c2c54c
                color_thresholds:
                  - value: 0
                    color: blue
                  - value: 20
                    color: green
                  - value: 40
                    color: red
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temp Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.temperature_158d0001c1c07a
                color_thresholds:
                  - value: 0
                    color: blue
                  - value: 22
                    color: green
                  - value: 25
                    color: red
              - type: custom:mini-graph-card
                name: Luftfuktighet Förråd
                height: 75
                show:
                  fill: fade
                entities:
                  - sensor.humidity_158d0001c1c07a
                color_thresholds:
                  - value: 0
                    color: blue
                  - value: 20
                    color: green
                  - value: 40
                    color: red

      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: switch.sovrum
            image: /local/ljusslinga.jpg
            tap_action:
              action: toggle
          - type: picture-entity
            entity: switch.brytare7
            image: /local/ljusslinga.jpg
            tap_action:
              action: toggle

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temp Sovrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.temperature_158d0001c2c4e4
            color_thresholds:
              - value: 0
                color: blue
              - value: 22
                color: green
              - value: 25
                color: red
          - type: custom:mini-graph-card
            name: Luftfuktighet Sovrum
            height: 75
            show:
                  fill: fade
            entities:
              - sensor.humidity_158d0001c2c4e4
            color_thresholds:
              - value: 0
                color: blue
              - value: 20
                color: green
              - value: 40
                color: red          

      - type: entities
        title: Utomhus
        show_header_toggle: false
        entities:
          - sensor.temperature_158d0001c16475
          - sensor.humidity_158d0001c16475
          - binary_sensor.door_window_sensor_158d0002011681
          - sensor.flower1_moisture
          - sensor.flower1_temperature
          - sensor.flower2_moisture
          - sensor.flower2_temperature

      - type: entities
        title: Övrigt
        show_header_toggle: false
        entities:
          - device_tracker.iphone
          - sensor.ssl_cert_expiry
          - sensor.custom_card_tracker
          - updater.updater

      - type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

      - type: weather-forecast
        entity: weather.smhi_skurup

      - type: history-graph
        title: 'Temperatures'
        hours_to_show: 144
        refresh_interval: 600
        entities:
          - sensor.temperature_158d0001c2c4e4
          - sensor.temperature_158d000201d362
          - sensor.temperature_158d0001c1c07a
          - sensor.temperature_158d0001c2c54c

      - type: custom:mini-media-player
        entity: media_player.vardagsrum
        name: Vardagsrum
        artwork: cover
        source: icon
        hide:
          shuffle: true

      - type: custom:mini-media-player
        entity: media_player.kok
        name: Kök
        artwork: cover
        source: icon
        hide:
          shuffle: true

  - title: Automations
    icon: mdi:auto-fix
    path: auto
    background: radial-gradient(white, skyblue)
    cards:
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - automation.hass_new_device_tracked
          - automation.hass_started
          - automation.hass_updater
          - automation.ifttt_trigger_automation
          - automation.renew_ssl_cert
          - automation.slack_ljus_vid_01_00
          - automation.slack_ljus_vid_20_00
          - automation.slack_ljus_vid_midnatt
          - automation.slack_xaoimi_gateway_rgb
          - automation.ssl_expiry_notification
          - automation.styr_xaoimi_gateway_rgb
          - automation.tand_ljus_60_min_innan_solnedgang

  - title: Batteries
    icon: mdi:battery-charging-40
    path: batt
    background: radial-gradient(white, crimson)
    cards:
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.flower1_battery
          - sensor.flower2_battery
