default_view:
 view: yes
 name: Home
 entities:
   - group.vardagsrum
   - group.uterum
   - group.sovrum
   - group.utomhus
   - group.markus
   - group.weather
   - history_graph.temperatures
   - history_graph.temperatures2
   - group.media