name: GitHub Actions

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    check-config:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - run: mv .dummy_secrets.yaml secrets.yaml
            - run: touch fullchain.pem
            - run: touch privkey.pem
            - name: Check HA config
              uses: kpucynski/action-ha-config-check@master
              with:
                  ha_version: 'latest'
